POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "User id of the note creator is at start sent along the request",
  "important": true,
  "userId": "5d380d49be1cef9cbad8af48"
}